# Generated by Django 5.0.3 on 2024-03-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='fruits', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Kartik', max_length=50)),
                ('lastname', models.CharField(default='Singhania', max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(default='karsingh@gmail.com', max_length=50)),
                ('city', models.CharField(default='Koregaon', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='Crocin', max_length=60)),
                ('productprice', models.IntegerField(default=300)),
                ('quantity', models.IntegerField(default=10)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robot.category')),
            ],
        ),
    ]
